### PR TITLE
updated function calls to support limit parameter for mandatory pagin…

### PR DESCRIPTION
**Pull request by rjrbytes**
Updated function calls in the module to support limit parameter for pagination. Default limit values match documented defaults from Duo, so this fixes the Json result size error as well.

### CODE REVIEW

**Comment by manuduo** [comment]
HI @mbegan and @rjrbytes this is Manu from Duo Security. Thank you for making updates to your wrapper library for handling pagination requests. It appears that you may have not covered all the API endpoints that now support pagination. In particular, we heard from a user (nnu.edu) that they are using your library and should hence be good with pagination. Turns out that their calls to https://duo.com/docs/adminapi#integrations are not being paged. Would be super awesome if you guys can look into this for us and the user at hand. 

We thank you for all your efforts to make using our Admin API easier!
-Manu 
(manu@duo.com)

**Comment by rjrbytes** [comment]
@manuduo it would be helpful to know exactly which call nnu.edu is using that is not paginated, since I don't use all of them and my time resources are limited. It's worth noting that @mbegan can't do this work since he doesn't have access to a Duo tenant with admin calls available (and your company didn't seem interested in providing one to assist in maintaining this module).

**Comment by mbegan** [comment]
@rjrbytes thanks for chiming in.  @manuduo he brings up a good point, clearly this module is useful for your customers.  I don't mind tinkering with it but have limited resources and no access.

**Comment by imaniac83** [comment]
Hi @manuduo, I found that the variable "**$parameters**" was not defined in the function "**duoGetIntegration**", therefore, the query "duoGetIntegration" returns an error:
"**_duoBuildCall : Cannot index into a null array.**"

It would be nice if you fixed it in the next release.

**Pull request merged**
